name: Execute Docker Image

on: workflow_dispatch

jobs:
  Excute:
    runs-on: ubuntu-latest
    steps:
    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker run zza1541/app-with-actions:latest
