name: SCP files From Actions to EC2
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -al
      - name: From Github Actions to AWS EC2 through SCP
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: app.jar
          target: /home/ubuntu/app
